### PR TITLE
[PBW-4128] add responsive values to skin config

### PR DESCRIPTION
**Pull request by mistermendez**

### CODE REVIEW

**Comment by mistermendez** [comment]
@lental @rcvrgs - can you pls review

**Comment by lenkid** [comment]
LGTM - this can be used to replace some of the hard coded stuff in our own code

That being said, was the lower threshold always 560? I thought it was 360. I very well could be wrong

**Comment by mistermendez** [comment]
Latest mocks show breakpoints as -

screen shot 2016-02-01 at 9 40 49 pm

**Comment by mistermendez** [comment]
I did not set small minWidth to 320 to catch all < 560

**Pull request merged**
