### PR TITLE
[PBW-3524] changing sizes according to Kristian

### PR DESCRIPTION
**Pull request by ksunika**

### CODE REVIEW

**Comment by ksunika** [comment]
@Matthew-C, @lental, could you look at this and merge?

**Comment by lental** [comment]
I wanna try these fonts real quick on our current iOS skin and see what happens

**Comment by lental** [comment]
okay a couple days ago there were 4 font changes:

Start Screen title font, description font, and
discovery title font, font of video names. 

This commit basically just reverts the start screen  font changes

Are we sure we don't want to reset the other fonts?

**Comment by ksunika** [comment]
@lental, after spending some time in discussions with Kristian, the only thing that he wanted to additionally change is Discovery font from 32 to 28. I pushed the change.

**Pull request merged**
