### PR TITLE
watermark updates.

### PR DESCRIPTION
**Pull request by wunnath**

### CODE REVIEW

**Comment by chibzu** [comment]
Looks good, just need to update the skin-schema to reflect the new properties.

**Comment by lental** [comment]
android resource is already there: https://github.com/ooyala/skin-config/blob/master/skin-schema.json#L991

**Comment by lental** [comment]
oh boy, but wait, the schema is not the same as the skin.  @wunnath  we'll have to look at that.

**Comment by lental** [comment]
@wunnath , you need to fix the schema and resolve conflicts before this can be merged

**Comment by wunnath** [comment]
raising new pull request as i was detached from this repo

**Pull request closed without merging**
