### PR TITLE
Changed JSON example to not be broken up into array

### PR DESCRIPTION
**Pull request by paulCern**
Keeping this JSON example in a single chunk, rather than broken into an array.  That way, it will appear as proper JSON in the generated HTML docs.

### CODE REVIEW

**Comment by lental** [comment]
sorry paul, the example doesn't parse in the validator.   Can you look into that?

node ./validate.js skin-schema.json skin.json

**Comment by paulCern** [comment]
Will do.

**Comment by lental** [comment]
closing for now, reopen if you figure out a good way to get'er done :)

**Comment by paulCern** [comment]
Will do.  Thanks.

**Pull request closed without merging**
