### PR TITLE
[PLAYER-22] - Added socialContent property

### PR DESCRIPTION
**Pull request by jpfranco**
https://jira.corp.ooyala.com/browse/PLAYER-22

### CODE REVIEW

**Comment by mistermendez** [comment]
heads up @lental @rcvrgs @pcaseooyala @akshaydch11

**Comment by lental** [comment]
we really need to discuss how we're going to specify what is web-supported and what is app-supported.  I don't have any solutions yet, but we need to think of something

**Comment by mistermendez** [comment]
@lental I like your suggestion of having separate config files (web.json, ios.json, etc) for each platform

**Comment by lental** [comment]
but the schema will need to be different.  that's the scary part

**Comment by mistermendez** [comment]
can we share the same schema and have different data that indicates platform support?

i.e. validation passes with this new `shareScreen.socialContent` param removed

**Comment by mistermendez** [comment]
👍  validation passed, works with html5-skin updates in `PLAYER-22`

**Pull request merged**
