### PR TITLE
[PBW-3308] skin config naming ordering

### PR DESCRIPTION
**Pull request by mistermendez**

### CODE REVIEW

**Comment by ksunika** [comment]
should be merged at the same time with https://github.com/ooyala/html5-skin/pull/168

**Comment by chibzu** [comment]
Do we have PBA's sign off on this change?

**Comment by mistermendez** [comment]
@lental can you sign-off? skin.json was updated with these changes - https://jira.corp.ooyala.com/browse/PBW-3308

**Comment by lental** [comment]
lgtm.  We will need to fix our code when we update our submodule, but that's not the biggest deal.

Thanks for cleaning up the config

**Pull request merged**
