### PR TITLE
[PBA-4717] add Thumb Color to scrubber bars

### PR DESCRIPTION
**Pull request by lental**
disable additional properties in the scrubber bar sections

### CODE REVIEW

**Comment by lental** [comment]
I can be convinced of different naming of the property :)

**Comment by lental** [comment]
bump.  can someone from PBW take a look at this?

**Comment by mistermendez** [comment]
We call it playhead. Can we call it `playheadColor` instead of thumbColor? Could be confused with thumbnail preview.

Otherwise LGTM.

**Comment by lental** [comment]
What do you think about "draggableColor"? "draggerColor"? IMHO i don't know if playheadColor is clear enough. any other opinions?

Do we also want to have configurable color for both the fill and the outline? how does "draggerFillColor" and "draggerOutlineColor" sound?

**Comment by mistermendez** [comment]
Searched the web, top 5 are:

1. scrubber button
2. scrub handel
3. slider handel
4. knob
5. handel

We call our thing "scrubber-bar" as long as we have "scrubber" in the name it should be clear and match industry standard. I like `scrubberHandelColor` and `scrubberHandelBorderColor`

**Comment by lental** [comment]
awesome!  I thought it was handle, so "scrubberHandleColor" and "scrubberHandleBorderColor".  is that okay?  I'll work on that

**Comment by lental** [comment]
updated. how's that look?

**Comment by mistermendez** [comment]
👍

**Pull request merged**
