### PR TITLE
[PBW-4287] making more space for volume slider, replacing volume icons

### PR DESCRIPTION
**Pull request by ksunika**

### CODE REVIEW

**Comment by ksunika** [comment]
@chibzu, @mistermendez: bump -- need this for new slider to have enough space

**Comment by chibzu** [comment]
Looks fine to me, @lental is this new width going to throw you guys off? Is there even a volume control in native land?

**Comment by ksunika** [comment]
new width is in "desktopContent" and "desktopAd" sections, doesn't interfere with mobile values.

**Comment by chibzu** [comment]
Oh, right. Duh. Looks good!

**Pull request merged**
